# Generated by Django 5.1.2 on 2024-10-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
