FIELD_WIDTH = 40
FIELD_HEIGHT = 24

BALL_RADIUS = 1
BALL_SPEED = 0.1

PADDLE_WIDTH = 1
PADDLE_HEIGHT = 4
# PADDLE_HEIGHT = FIELD_HEIGHT / 4
PADDLE_SPEED = 0.1
# PADDLE_Y = (FIELD_HEIGHT - PADDLE_HEIGHT) / 2
# PADDLE_Y = ((FIELD_HEIGHT / 2) - )
