secretKey=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
path=src/blockchain/foundry
file=src/FactoryTournament.sol:TournamentFactory
rpc=127.0.0.1:8545

all:
	forge create $(file) -r $(rpc) --private-key $(secretKey)